### ISSUE TITLE
Error: Unsupported brand channel name

### ISSUE THREAD

**Issue by yawn999** [DuckySoLucky/hypixel-discord-chat-bridge#1]
https://www.toptal.com/developers/hastebin/udofaqexag.apache

**Comment by DuckySoLucky** [comment]
Please give more information. Have u installed all packages and edited config.json?

**Comment by yawn999** [comment]
![msedge_HeOcY08GY6](https://user-images.githubusercontent.com/55554025/166959896-6eb8bec2-2533-4dd6-8e48-573a29bf0a6b.png)

**Comment by DuckySoLucky** [comment]
Does the code have root access?
