### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by RagingEnby** [DuckySoLucky/hypixel-discord-chat-bridge#131]
I've spent hours trying to figure out the cause of this and just cannot figure it out please help

https://pastebin.com/TXFQKV23

**Comment by DuckySoLucky** [comment]
Hello, contact me on the discord DuckySoLucky#5181 for faster responses.

You have node v18.12.1 and canvas doesn't like that. Try reverting to node v16 and reinstall packages
