### ISSUE TITLE
Update reply system

### ISSUE THREAD

**Issue by Kathund** [DuckySoLucky/hypixel-discord-chat-bridge#138]
The replay system uses the discord users name and not there nick. This can be confusing to people ingame when there trying to figure out who there talking to.

Photo of the current system - https://kath.stay-mad.lol/h7hres85.png

**Comment by DuckySoLucky** [comment]
> The replay system uses the discord users name and not there nick. This can be confusing to people ingame when there trying to figure out who there talking to.
> 
> Photo of the current system - https://kath.stay-mad.lol/h7hres85.png

yes

**Comment by Kathund** [comment]
@DuckySoLucky i dont think this was ever fixed? 
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/55346310/4c0aacf6-6cf6-4413-9726-66fbfc373176)

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky i dont think this was ever fixed? ![image](https://private-user-images.githubusercontent.com/55346310/309476994-4c0aacf6-6cf6-4413-9726-66fbfc373176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODc1OTgsIm5iZiI6MTcwOTM4NzI5OCwicGF0aCI6Ii81NTM0NjMxMC8zMDk0NzY5OTQtNGMwYWFjZjYtNmNmNi00NDEzLTk3MjYtNjZmYmZjMzczMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDEzNDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NmE2MWMwMTYwZmYwYTAwODY3N2E3ZTY5MGU2YjdkZGZlMTk2NjE4MzkyNWQ1YzNmNzVkYWU0MjYwNjEwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.deSYq4C0O8uaW9ogio19WbwIShfwXSzMcsEEgpWHVh0)

what's wrong with that?

**Comment by Kathund** [comment]
> > @DuckySoLucky i dont think this was ever fixed? ![image](https://private-user-images.githubusercontent.com/55346310/309476994-4c0aacf6-6cf6-4413-9726-66fbfc373176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODc1OTgsIm5iZiI6MTcwOTM4NzI5OCwicGF0aCI6Ii81NTM0NjMxMC8zMDk0NzY5OTQtNGMwYWFjZjYtNmNmNi00NDEzLTk3MjYtNjZmYmZjMzczMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDEzNDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NmE2MWMwMTYwZmYwYTAwODY3N2E3ZTY5MGU2YjdkZGZlMTk2NjE4MzkyNWQ1YzNmNzVkYWU0MjYwNjEwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.deSYq4C0O8uaW9ogio19WbwIShfwXSzMcsEEgpWHVh0)
> 
> what's wrong with that?

wouldnt it make more sense to show the nickname of the user 
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/55346310/4ee3ef0d-82d1-4414-a7dd-df62e2077c4c)

**Comment by DuckySoLucky** [comment]
make a PR?

**Comment by Kathund** [comment]
> make a PR?

sure eta 5 years
