### ISSUE TITLE
Message overflow allows users to execute any commands as bot user

### ISSUE THREAD

**Issue by DSSoftware** [DuckySoLucky/hypixel-discord-chat-bridge#168]
# What's the issue:
Slicing long messages for several messages allows possible unauthorized command executions.

# How to reproduce:
Command like this
`1234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234567891234/gc hey` would execute command `/gc hey` as a bot, but it needs adjustments so it slices the message right at the end of the placeholder string and sends the payload as another message.

# How to fix:
Simplest option is to remove slicing entirely OR add `IGN >` at the end of sliced string.

**Comment by DSSoftware** [comment]
### Temporary solution
Strip all message contents after certain message length (still testing).

### Example of overflow
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/56971105/490a1302-c56d-437b-93f2-9b3aba498421)
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/56971105/38630b21-7b64-4892-8bc2-b0b4fa8bfc04)

**Comment by DuckySoLucky** [comment]
Heya, thanks gonna check that out once I'm free

**Comment by DSSoftware** [comment]
#169 is done and should fix this issue.

**Comment by Kathund** [comment]
@DuckySoLucky close (tested dosent work anymore)

**Comment by DSSoftware** [comment]
kathund said it doesnt work anymore xd
