### ISSUE TITLE
!networth minecraft command prioritizes ironman profile over selected profile

### ISSUE THREAD

**Issue by Ninjune** [DuckySoLucky/hypixel-discord-chat-bridge#2]
All of the images below the user did the command on their main.

![image](https://user-images.githubusercontent.com/26883922/193465848-46f28e51-dfff-461f-8217-d99d05c2c1b8.png)
![image](https://user-images.githubusercontent.com/26883922/193465888-bc1c6442-b667-412b-9cb3-dd66b9a90306.png)
![image](https://user-images.githubusercontent.com/26883922/193465989-74e943e3-4762-4e97-a364-451c8c998f0d.png)

Bot Version 3.1.3 
NodeJS Version 18.9.0

**Comment by DuckySoLucky** [comment]
Hey, this has been fixed. But I haven't made release for that so just git clone instead of downloading release

**Comment by DuckySoLucky** [comment]
Here's commit https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/blob/main/API/functions/getLatestProfile.js
