### ISSUE TITLE
Autoaccept requirements not getting Senither Weight

### ISSUE THREAD

**Issue by rdbtCVS** [DuckySoLucky/hypixel-discord-chat-bridge#204]
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/87152661/6135586e-1b1f-4de4-8a88-05698ac7911d)

**Comment by DuckySoLucky** [comment]
Heya, thanks for info expect fix within 2-3 business days

**Comment by Kathund** [comment]
@DuckySoLucky was this ever fixed

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky was this ever fixed

no
