### ISSUE TITLE
[Suggestion] /online player counts

### ISSUE THREAD

**Issue by Kathund** [DuckySoLucky/hypixel-discord-chat-bridge#212]
When running /online it shows whos online with there ranks but it would be cool at the bottom its showing the amount of people online and the amount in the guild like it shows on hypixel

**Comment by Zickles** [comment]
should be pretty easy to do i can make a pr sometime within the next 3-5 businesses days (yes businesses days)

**Comment by Kathund** [comment]
already a thing
