### ISSUE TITLE
Images don't send from Diascord to in-game unless there's text with it.

### ISSUE THREAD

**Issue by kwissss** [DuckySoLucky/hypixel-discord-chat-bridge#231]
Images don't send from Discord to In-Game unless there's text with it.

Message mode set to bot.

This would send:
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/16555169/5b474691-29fd-4040-aa0e-7c40e3e5f2c4)

This wouldn't:
![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/16555169/48aa578b-7405-458d-96e1-81f1bfde5ecf)

**Comment by DuckySoLucky** [comment]
Heya, yeah I'm aware sadly the images themselves aren't caught on the message event by discord.js unless there's some kind of text
