### ISSUE TITLE
Discord Users with only an emoji as their name makes the Bridge Bot send their message without their name

### ISSUE THREAD

**Issue by kwissss** [DuckySoLucky/hypixel-discord-chat-bridge#232]
Discord Users with only an emoji as their name makes the Bridge Bot send their message without their name

**Comment by DuckySoLucky** [comment]
Fixed in https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/commit/81a1949685a35ce62430d777a18747fb26d21398
