### ISSUE TITLE
Messages starting with "Party >" in guild chat doesn't get sent.

### ISSUE THREAD

**Issue by kwissss** [DuckySoLucky/hypixel-discord-chat-bridge#234]
Messages starting with "**Party >**" in the guild chat on Minecraft doesn't get sent to Discord when using the bot message mode. I haven't tested with other message modes.

As you can see from the bot logs and minecraft images below the message didn't get sent as it started with **Party >**

![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/16555169/b9788af1-4788-422c-bb4e-cc7d3a973acf)

![image](https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/assets/16555169/18f23104-894b-4f62-a3cd-fe67973cbc27)

**Comment by DuckySoLucky** [comment]
Pushed a fix, `git pull` for a change

**Comment by kwissss** [comment]
We did some more testing now and it seems to be that any combination of any Text followed with a > doesn't get sent.

The following wouldn't get sent, for example:
```
Text >
Party >
Anything >
```

**Comment by DuckySoLucky** [comment]
Yeah it's the regex which is used to detect discord message, made so it doesn't flag Party messages only

**Comment by kwissss** [comment]
awesome, thank you! ❤️

**Comment by kwissss** [comment]
we tested it again now and didn't work
