### ISSUE TITLE
Add a filter to chat messages from Discord to Minecraft to prevent "IP Addresses" from being sent

### ISSUE THREAD

**Issue by kwissss** [DuckySoLucky/hypixel-discord-chat-bridge#240]
This message got bridge bot muted:
`leaking for 1 074 824 100 coins`

The message came through to Hypixel as:
`Guild > [VIP] BRIDGE_BOT: USERNAME: leaking for [IP Address Removed] coins`

Which resulted in:
`Bot is currently muted for a Major Chat infraction.`
`Mute will expire in 1d`

It seems Hypixel uses the following regex to look for IP Addresses: `(\d{3}[. ]?){4}`. They don't limit the values at max 255 as the message above contained 824, which is more than the max.

I suggest a filter is put in place to prevent other bots from being muted and investigated to be (potentially) banned - even though it was a false mute, it leads the staff to investigate the "IP Address" and the context, thus discovering the bot.

**Comment by DuckySoLucky** [comment]
we love Hypixel, can you replace the current regex with the right one if u don't mind? it should be inside `src/discord/handlers/Message handler.js` iirc

**Comment by kwissss** [comment]
Hmm. I looked into the file you mentioned and the bot was the one replacing the numbers with `[IP Address Removed]`. I assumed it was Hypixel that replaced it. Perhaps then it was the combination of the word `leaking` and the message sent containing `IP Address`?

**Comment by DuckySoLucky** [comment]
Yeah, probably should be replaced with something like `[Content Redacted]`

**Comment by DuckySoLucky** [comment]
ty <3
