### ISSUE TITLE
Spammed type error when starting

### ISSUE THREAD

**Issue by exilliuz** [DuckySoLucky/hypixel-discord-chat-bridge#59]
**This error is spammed many times and no messages are shared:**

TypeError: Cannot read properties of undefined (reading 'send')
    at DiscordManager.onBroadcast (C:\Users\xerius\Downloads\hypixel-discord-chat-bridge-3.1.7.1\hypixel-discord-chat-bridge-3.1.7.1\src\discord\DiscordManager.js:149:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'send')

As well as this, the discord bot remains offline.

**Comment by DuckySoLucky** [comment]
Heya exilliuz,

Thank you for reporting this issue. I have attempted to reproduce the bug, but have been unable to do so. The only potential explanation I can think of at this time is that the config property may not have been properly set up. It is possible that you have missed one of the channel fields in the config, or that the bot does not have access to the relevant channels.

Sincerely,
DuckySoLucky

**Comment by exilliuz** [comment]
Ah, I see, I'll check as soon as I can if I can find something I might not have filled in. If everything seems fine in my config to me, would I be able to send it to you via discord?

**Comment by DuckySoLucky** [comment]
> Ah, I see, I'll check as soon as I can if I can find something I might not have filled in. If everything seems fine in my config to me, would I be able to send it to you via discord?

Sure, my Discord is [DuckySoLucky#5181](https://discord.com/users/486155512568741900)
