### ISSUE TITLE
[Suggestion] Verify system

### ISSUE THREAD

**Issue by oodvg** [DuckySoLucky/hypixel-discord-chat-bridge#84]
A way for users to verify if they are in the guild or not.

**Comment by DuckySoLucky** [comment]
What do you mean by that? Command or?

**Comment by yawn999** [comment]
well, A System in general.

**Comment by DuckySoLucky** [comment]
U mean only guild members can use guild chat or?

**Comment by yawn999** [comment]
you can say that, yes.

**Comment by DuckySoLucky** [comment]
Can you contact me on discord and tell me more details?
